# Cross-platform task runner for ai-org-simulation.
# Recipes here are the single source of truth for common dev commands.

set windows-shell := ["powershell.exe", "-NoLogo", "-NoProfile", "-Command"]
set shell := ["bash", "-c"]

# Make ``backend.*`` and ``scripts.*`` imports work from any recipe,
# regardless of how Python resolves CWD (uv run, alembic CLI, etc.).
export PYTHONPATH := justfile_directory()

# List all available recipes.
default:
    @just --list

# Install Python deps into .venv via uv.
setup:
    uv sync
    @echo "Setup complete. Try: just db-up && just dev"

# Run FastAPI dev server with auto-reload.
dev:
    uv run uvicorn backend.main:app --reload --app-dir .

# Start the local Postgres container in the background.
db-up:
    docker compose up -d postgres

# Stop and remove all docker-compose services.
db-down:
    docker compose down

# Apply all pending migrations to local Postgres.
db-migrate:
    uv run alembic upgrade head

# Create a new autogenerated migration. Usage: just db-revision "add foo table"
db-revision message:
    uv run alembic revision --autogenerate -m "{{message}}"

# Drop & recreate the local DB volume, then re-run migrations from scratch.
# Use when schema diverges and you want a clean slate (DESTRUCTIVE).
db-reset:
    uv run python scripts/dev/db_reset.py

# Wipe + repopulate every raw table from datasets/raw/*/*.csv.
# Idempotent — running it twice gives the same final state.
seed:
    uv run python scripts/dev/seed_all.py

# One-shot bootstrap for a fresh clone:
# install deps -> start docker -> apply migrations.
bootstrap:
    uv sync
    docker compose up -d postgres
    uv run python scripts/dev/wait_for_postgres.py
    uv run alembic upgrade head
    @echo "Bootstrap complete. Try: just dev"

# Lint check (no changes).
lint:
    uv run ruff check .
    uv run ruff format --check .

# Auto-format and auto-fix lints.
fmt:
    uv run ruff format .
    uv run ruff check --fix .

# Run the test suite.
test:
    uv run pytest
