"""initial employees table

Revision ID: 17d3089a2683
Revises: 
Create Date: 2026-05-22 03:02:10.156181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d3089a2683'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('employee_id', sa.String(length=32), nullable=False),
    sa.Column('employee_name', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('tenure_years', sa.Float(), nullable=False),
    sa.Column('employment_status', sa.String(length=16), nullable=False),
    sa.Column('employment_type', sa.String(length=16), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('team', sa.String(length=64), nullable=False),
    sa.Column('job_family', sa.String(length=64), nullable=False),
    sa.Column('job_title', sa.String(length=64), nullable=False),
    sa.Column('job_level', sa.String(length=16), nullable=False),
    sa.Column('manager_id', sa.String(length=32), nullable=True),
    sa.Column('work_location', sa.String(length=64), nullable=False),
    sa.Column('education_level', sa.String(length=32), nullable=False),
    sa.Column('base_salary_krw', sa.Integer(), nullable=False),
    sa.Column('bonus_krw', sa.Integer(), nullable=False),
    sa.Column('last_performance_rating', sa.String(length=8), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=False),
    sa.Column('kpi_score', sa.Float(), nullable=False),
    sa.Column('okr', sa.String(length=255), nullable=False),
    sa.Column('competency_score', sa.Float(), nullable=False),
    sa.Column('peer_review_score', sa.Float(), nullable=False),
    sa.Column('manager_review_score', sa.Float(), nullable=False),
    sa.Column('self_review_score', sa.Float(), nullable=False),
    sa.Column('promotion_eligible', sa.Boolean(), nullable=False),
    sa.Column('promotion_recommended', sa.Boolean(), nullable=False),
    sa.Column('last_promotion_date', sa.Date(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('absence_days_12m', sa.Integer(), nullable=False),
    sa.Column('overtime_hours_12m', sa.Integer(), nullable=False),
    sa.Column('training_hours_12m', sa.Integer(), nullable=False),
    sa.Column('certifications_count', sa.Integer(), nullable=False),
    sa.Column('disciplinary_actions_12m', sa.Integer(), nullable=False),
    sa.Column('remote_work_days_12m', sa.Integer(), nullable=False),
    sa.Column('turnover_risk_score', sa.Float(), nullable=False),
    sa.Column('github_id', sa.String(length=64), nullable=True),
    sa.Column('slack_user_id', sa.String(length=64), nullable=True),
    sa.Column('jira_account_id', sa.String(length=64), nullable=True),
    sa.Column('google_calendar_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_index(op.f('ix_employees_manager_id'), 'employees', ['manager_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_manager_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
