"""add github_activities table

Revision ID: 1f763545df25
Revises: 17d3089a2683
Create Date: 2026-05-22 03:15:28.364548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f763545df25'
down_revision: Union[str, Sequence[str], None] = '17d3089a2683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('github_id', sa.String(length=64), nullable=False),
    sa.Column('measured_from', sa.Date(), nullable=False),
    sa.Column('measured_to', sa.Date(), nullable=False),
    sa.Column('commit_count_3m', sa.Integer(), nullable=False),
    sa.Column('pr_count_3m', sa.Integer(), nullable=False),
    sa.Column('merged_pr_count_3m', sa.Integer(), nullable=False),
    sa.Column('closed_unmerged_pr_count_3m', sa.Integer(), nullable=False),
    sa.Column('repository_contribution_count', sa.Integer(), nullable=False),
    sa.Column('contributed_repositories', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetch_status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id', 'measured_from', 'measured_to', name='uq_github_activity_window')
    )
    op.create_index(op.f('ix_github_activities_github_id'), 'github_activities', ['github_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_activities_github_id'), table_name='github_activities')
    op.drop_table('github_activities')
    # ### end Alembic commands ###
