"""add jira_activities table

Revision ID: 3c92329f4c7e
Revises: a7d08a9bbab2
Create Date: 2026-05-22 04:14:29.968409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c92329f4c7e'
down_revision: Union[str, Sequence[str], None] = 'a7d08a9bbab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jira_account_id', sa.String(length=64), nullable=False),
    sa.Column('measured_from', sa.Date(), nullable=False),
    sa.Column('measured_to', sa.Date(), nullable=False),
    sa.Column('assigned_issue_count', sa.Integer(), nullable=False),
    sa.Column('reported_issue_count', sa.Integer(), nullable=False),
    sa.Column('completed_issue_count', sa.Integer(), nullable=False),
    sa.Column('issue_type_mix', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority_mix', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('avg_cycle_time', sa.Float(), nullable=False),
    sa.Column('overdue_issue_count', sa.Integer(), nullable=False),
    sa.Column('estimation_accuracy', sa.Float(), nullable=False),
    sa.Column('worklog_hours', sa.Float(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('avg_comment_response_time', sa.Float(), nullable=False),
    sa.Column('collaboration_touchpoints', sa.Integer(), nullable=False),
    sa.Column('status_transition_count', sa.Integer(), nullable=False),
    sa.Column('avg_time_in_status', sa.Float(), nullable=False),
    sa.Column('reopened_issue_count', sa.Integer(), nullable=False),
    sa.Column('scope_change_count', sa.Integer(), nullable=False),
    sa.Column('task_breakdown_count', sa.Integer(), nullable=False),
    sa.Column('sprint_participation', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('sprint_completion_rate', sa.Float(), nullable=False),
    sa.Column('context_switching_score', sa.Float(), nullable=False),
    sa.Column('autonomy_score', sa.Float(), nullable=False),
    sa.Column('ownership_score', sa.Float(), nullable=False),
    sa.Column('bottleneck_risk', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetch_status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jira_account_id', name='uq_jira_activity_user')
    )
    op.create_index(op.f('ix_jira_activities_jira_account_id'), 'jira_activities', ['jira_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jira_activities_jira_account_id'), table_name='jira_activities')
    op.drop_table('jira_activities')
    # ### end Alembic commands ###
