"""hr schema update: drop team/job_family/job_title/job_level/okr, add job_category_code, rename google_calendar_id to google_email

Revision ID: 612b2651c631
Revises: 3c92329f4c7e
Create Date: 2026-05-22 04:25:45.660919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612b2651c631'
down_revision: Union[str, Sequence[str], None] = '3c92329f4c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('job_category_code', sa.String(length=16), nullable=False))
    op.add_column('employees', sa.Column('google_email', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_employees_job_category_code'), 'employees', ['job_category_code'], unique=False)
    op.drop_column('employees', 'job_title')
    op.drop_column('employees', 'team')
    op.drop_column('employees', 'job_level')
    op.drop_column('employees', 'okr')
    op.drop_column('employees', 'job_family')
    op.drop_column('employees', 'google_calendar_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('google_calendar_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('job_family', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('okr', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('job_level', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('team', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('job_title', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_employees_job_category_code'), table_name='employees')
    op.drop_column('employees', 'google_email')
    op.drop_column('employees', 'job_category_code')
    # ### end Alembic commands ###
