"""add calendar_activities table

Revision ID: 8cb32450ab06
Revises: 612b2651c631
Create Date: 2026-05-22 04:34:40.790432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cb32450ab06'
down_revision: Union[str, Sequence[str], None] = '612b2651c631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('google_email', sa.String(length=128), nullable=False),
    sa.Column('calendar_id', sa.String(length=128), nullable=False),
    sa.Column('measured_from', sa.Date(), nullable=False),
    sa.Column('measured_to', sa.Date(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('meeting_count', sa.Integer(), nullable=False),
    sa.Column('total_meeting_minutes', sa.Integer(), nullable=False),
    sa.Column('avg_meeting_duration_minutes', sa.Float(), nullable=False),
    sa.Column('all_day_event_count', sa.Integer(), nullable=False),
    sa.Column('active_hours', sa.String(length=16), nullable=False),
    sa.Column('early_late_meeting_ratio', sa.Float(), nullable=False),
    sa.Column('weekend_meeting_ratio', sa.Float(), nullable=False),
    sa.Column('focus_time_count', sa.Integer(), nullable=False),
    sa.Column('focus_time_minutes', sa.Integer(), nullable=False),
    sa.Column('fragmented_calendar_score', sa.Float(), nullable=False),
    sa.Column('no_meeting_block_count', sa.Integer(), nullable=False),
    sa.Column('organizer_event_count', sa.Integer(), nullable=False),
    sa.Column('attendee_event_count', sa.Integer(), nullable=False),
    sa.Column('organizer_ratio', sa.Float(), nullable=False),
    sa.Column('attendee_count_avg', sa.Float(), nullable=False),
    sa.Column('large_meeting_ratio', sa.Float(), nullable=False),
    sa.Column('external_meeting_ratio', sa.Float(), nullable=False),
    sa.Column('accepted_attendee_count', sa.Integer(), nullable=False),
    sa.Column('declined_attendee_count', sa.Integer(), nullable=False),
    sa.Column('tentative_attendee_count', sa.Integer(), nullable=False),
    sa.Column('no_response_ratio', sa.Float(), nullable=False),
    sa.Column('recurring_event_count', sa.Integer(), nullable=False),
    sa.Column('recurring_meeting_ratio', sa.Float(), nullable=False),
    sa.Column('busy_minutes', sa.Integer(), nullable=False),
    sa.Column('working_location_count', sa.Integer(), nullable=False),
    sa.Column('working_location_mix', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('event_update_count', sa.Integer(), nullable=False),
    sa.Column('meeting_provider_mix', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetch_status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_email', 'calendar_id', name='uq_calendar_activity_user_calendar')
    )
    op.create_index(op.f('ix_calendar_activities_google_email'), 'calendar_activities', ['google_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_activities_google_email'), table_name='calendar_activities')
    op.drop_table('calendar_activities')
    # ### end Alembic commands ###
