"""add slack_activities table

Revision ID: b49c9f991eff
Revises: 1f763545df25
Create Date: 2026-05-22 03:31:12.418366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b49c9f991eff'
down_revision: Union[str, Sequence[str], None] = '1f763545df25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_activities',
    sa.Column('slack_user_id', sa.String(length=64), nullable=False),
    sa.Column('measured_from', sa.Date(), nullable=False),
    sa.Column('measured_to', sa.Date(), nullable=False),
    sa.Column('accessible_conversations', sa.Integer(), nullable=False),
    sa.Column('user_conversations', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('conversation_members', sa.Integer(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('message_events', sa.Integer(), nullable=False),
    sa.Column('thread_replies', sa.Integer(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('collaboration_frequency', sa.Integer(), nullable=False),
    sa.Column('top_collaborators', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('avg_response_time', sa.Float(), nullable=False),
    sa.Column('communication_balance', sa.Float(), nullable=False),
    sa.Column('active_hours', sa.String(length=16), nullable=False),
    sa.Column('night_activity_ratio', sa.Float(), nullable=False),
    sa.Column('multitasking_score', sa.Float(), nullable=False),
    sa.Column('leadership_score', sa.Float(), nullable=False),
    sa.Column('dependency_score', sa.Float(), nullable=False),
    sa.Column('bottleneck_risk', sa.Float(), nullable=False),
    sa.Column('collaboration_style', sa.String(length=32), nullable=False),
    sa.Column('autonomy_score', sa.Float(), nullable=False),
    sa.Column('burnout_risk', sa.Float(), nullable=False),
    sa.Column('decision_latency', sa.Float(), nullable=False),
    sa.Column('slack_user_profile', sa.Text(), nullable=False),
    sa.Column('slack_users', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetch_status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('slack_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_activities')
    # ### end Alembic commands ###
